print("What is your name?")
name = str(input())
print("How old are you?")
age = int(input())
print("How tall are you (in meters)?")
height = float(input())
print("How much do you weigh (in kilograms)?")
weight = float(input())
print(weight / height ** 2)